### ISSUE TITLE
Erro para compilar no MacOS

### ISSUE THREAD

**Issue by rodrigopg** [killerall/advpl-vscode#213]
Boa tarde,

Atualizei para a nova versão 0.10.3 porem ainda não consigo compilar no MacOS

Instalei o OpenSSL e já verifiquei que o arquivo AdvplDebugBridgeC tem permisão de execução.

Segue erro gerado:
[2018-05-25 12:59:30.629] [renderer4] [error] spawn /Users/rodrigo/.vscode/extensions/KillerAll.advpl-vscode-0.10.3/bin/alpha/mac/AdvplDebugBridgeC ENOENT: Error: spawn /Users/rodrigo/.vscode/extensions/KillerAll.advpl-vscode-0.10.3/bin/alpha/mac/AdvplDebugBridgeC ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by rodrigopg** [comment]
Rodrigos-MacBook-Pro:bin rodrigo$ openssl version
LibreSSL 2.2.7

**Comment by killerall** [comment]
Boa tarde,

A versao 0.10.3 saiu com o diretorio do bin do mac errado.
Tem um bin a mais.

Da uma olhada nesta issue, la o rapaz consegui copiar e mostrou o caminho certo:
https://github.com/killerall/advpl-vscode/issues/209

Deve sair ate segundo uma correção para isso.

**Comment by rodrigopg** [comment]
Boa tarde,

Consegui resolver.. o que ocorreu é que o plugin instala o arquivo na pasta:
~/.vscode/extensions/KillerAll.advpl-vscode-0.10.3/bin/alpha/mac/**bin**

porem lê o mesmo na pasta:
 ~/.vscode/extensions/KillerAll.advpl-vscode-0.10.3/bin/alpha/mac/

apenas copiei o AdvplDebugBridgeC  para a pasta anterior mac/

**Comment by rodrigopg** [comment]
Eita. vc respondeu rápido kkkkk
foi isso mesmo, deu certo! 
Valeu xará!
